### ISSUE TITLE
SOA Serial resets from set Value when enabling Autogenerate, but creates lower Value than before

### ISSUE THREAD

**Issue by Stathogon** [peteeckel/netbox-plugin-dns#266]
**Versions**
NetBox Version: 4.0.2
NetBox DNS Version: 1.0.0
Python Version:3.11

**Describe the bug**
When I use already existing Zones and migrate them to Netbox, the Serial atm is set to the Date with a increment suffix. But the autogenerated Serial is lower than the value. When i set it to a specific value (above the value before migration), i have to disable the auto generate feature and set it manually. When i set it to automatic again after that, it jumps to the lower value, therefore the Bind-Minions dont update their values. 

**To Reproduce**
1. set manual serial
2. enable automatic Serial
3. the value goes to the Serial before

**Expected result**
When i set it to automatic and enter a manual value, it should start incrementing from there.

**Actual result**
The auto generated Value is set again (which could be lower than the Value before).

**Comment by peteeckel** [comment]
Hi @Stathogon, this is a known problem and unfortunately not easy to solve.

The problem is that the automatically generated serial numbers are created from the epoch (seconds since Jan 1, 1970, 00:00:00 UTC) to keep generation simple, safe and straightforward (it can be done within the database, for example). When you switch from one of the common schemes like `yyyymmddxx` to that, the serial number unfortunately goes backwards, causing some trouble with DNS replication. Unfortunately, this format isn't very well suited for automatic generation of serials, and there is no well-defined 'standard' way of doing it.

There are some ways to resolve this:
* Save the highest seen serial number of a zone and add some value (derived from the time stamp when that serial number was seen and the current epoch) to it to create the final serial number
* Use an arbitrary offset to keep the epoch-related serial number higher than the schema mentioned above
* Reset the serial number of the DNS mirrors to the new schema. Modern BIND implementations can do that by setting the serial to 0 temporarily, but there are other methods as well that make use of the fact that the serial in DNS is defined as a 32 bit number that wraps at some point - usually adding 2147483647, synchronising the slaves (**all** of them!) and then setting it to the new value works.

That said, it is definitely unsatisfactory to have this kind of problem, so I'll think of some better solution. The good thing is that it usually is a one-off issue, so documenting a solution might be enough.

I have, however another idea that is easy to implement: Your test case involves setting a serial number manually, then switching to automatic generation afterwards. **That** can be caught easily by not allowing a switch from manual to automatic when the current serial is higher than the one created automatically would be. That would give the user the opportunity to first fix the problem, then switch to automatic generation.

**Comment by Stathogon** [comment]
Solved it by deleting the cached files on the Minions. the Serial manipulation sadly didnt worked for me, but that could be a understanding problem on my part

**Comment by peteeckel** [comment]
If you have shell access to the slaves that works as well, yes. You could also `rndc retransmit` the zones if you're running BIND.

The process of increasing the zones is a bit involved, but it should work as well. You need to be sure that you increase the serial by less than 2**31 in one step, then wait for the slaves to catch up, and then do the next step. 

If your slaves won't pick up the change immediately, possibly `notify` does not work (due to firewall restrictions or BIND ACL issues, or some other reason). In this case you must wait for the refresh interval to elapse, which is when the slaves will re-query the zones by themselves. This might take a while, depending on the zone's 'SOA Refresh' setting.

Anyway, I added some checks to NetBox DNS to make sure situations like this at least don't go unnoticed.
