### ISSUE TITLE
Pressing save on a record after editing only a custom field doesn't save changes

### ISSUE THREAD

**Issue by BarrieAlmond** [peteeckel/netbox-plugin-dns#472]
**Versions**
NetBox Version: 4.1.6
NetBox DNS Version: 1.1.5
Python Version: 3.11

**Describe the bug**
If you edit a DNS record with a custom field, and ONLY make a change to the custom field, pressing Save doesn't record the changes. "A" records seem to be the exception.

**To Reproduce**
Add a custom field to object type Netbox DNS > Record (I used a boolean)
Create a new CNAME, TXT, or MX record (I didn't try others except A records which don't have the issue) and set the custom field's boolean value
Edit the newly created record, flip the custom field's boolean value but changing no other fields and press save

**Expected result**
The record should be updated with the custom field's new value

**Actual result**
The record is displayed but the custom field still shows the old value. The record's "updated" time and the change log don't record anything. A temporary message appears in the bottom right with a green header and a tick saying "Modified Record"

**Comment by peteeckel** [comment]
I can confirm the behaviour you're seeing, and the bug is actually two bugs.

1. When saving custom field data for comparison (to detect if anything has changed), the code apparently already gets the new state of the custom field data, which causes a change in custom field data to go unnoticed.
2. With A records, for some reason the (internally used) `ip_address` field is always marked as changed. That causes your problem not to appear with A (and AAAA and PTR) records.

I'm currently investigating both issues and hope to have a fix available soon.

**Comment by peteeckel** [comment]
>I can confirm the behaviour you're seeing, and the bug is actually two bugs.
 
Did I say two? I'll raise that to four :-) #472, #474, #475 and #476 are fixed now :-)

This was the single most efficient issue in the history of this project - thanks! 👍

**Comment by BarrieAlmond** [comment]
Great job! Thanks for looking at this, I'll give it a try with the next release.
